name: Format C# Code

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  format:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.base.sha }}
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9'

    - name: Make dotnet-format.sh executable
      run: chmod +x ./dotnet-format.sh
    
    - name: Run dotnet format
      run: ./dotnet-format.sh
      env:
        PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
    
    - name: Commit formatted changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: 'GitHub Action'
        author_email: 'action@github.com'
        message: 'Apply dotnet format formatting'
        add: '.'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}