name: Format C# Code

on:
  pull_request:
    branches: [ main ]

# Ensure formatting runs sequentially for the same PR
concurrency:
  group: format-${{ github.event.pull_request.number }}
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

jobs:
  format:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 3  # Need depth of 3 to check for merge commits (HEAD + both parents)
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9'
    
    - name: Run dotnet format
      run: |
        # Run from repository root to ensure correct file paths
        cd $GITHUB_WORKSPACE
        ./.github/workflows/dotnet-format.sh
    
    - name: Commit formatted changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: 'GitHub Action'
        author_email: 'action@github.com'
        message: 'Apply dotnet format formatting'
        add: '.'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}